script:
  path: ./static/scripts
settings:
  application:
    mode: prod  # dev开发环境 test测试环境 prod线上环境
    host: 0.0.0.0
    name: ferry
    port: 8002
    readtimeout: 1
    writertimeout: 2
    domain: localhost:8002
    ishttps: false
  ssl:
    key: keystring
    pem: temp/pem.pem
  jwt:
    secret: ferry
    timeout: 3600
  database:
    name: ferry
    dbtype: mysql
    host: 127.0.0.1
    password: 123456
    port: 3306
    username: root
  redis:
    host: 127.0.0.1
    port: 6379
  email:
    alias: ferry
    host: smtp.163.com
    pass: your password
    port: 465
    user: your username
  gorm:
    logmode: 0
    maxidleconn: 0
    maxopenconn: 20000
  domain: http://192.168.0.100:9527
  ldap:
    host: 127.0.0.1
    port: 389
  log:
    compress: 1
    consolestdout: 1
    filestdout: 1
    level: info
    localtime: 1
    maxAge: 30
    maxbackups: 300
    maxsize: 10240
    path: ./logs/ferry.log
